# Generated by Django 5.0.7 on 2024-08-07 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_statusmedicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='statusmedicines',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
